on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy on Kapstan
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy on Kapstan
        id: kapstan
        uses: kapstan-io/deployment-action@v0.7
        with:
          application_name: wwwdevopsbingo
          image_tag: [YOUR_IMAGE_TAG_TO_DEPLOY]
          pre_deploy_image_tag: [YOUR_PRE_DEPLOY_IMAGE_TAG_TO_DEPLOY if any, otherwise omit]
          kapstan_api_key: 9f8493d2b89ddd23c7153c020bc61544 # fetch from secrets
          wait_for_deployment: true