name: Build and Publish

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build-and-publish:
    name: Publish
    runs-on: ubuntu-latest
    outputs:
      imageTag: ${{ steps.set_tag.outputs.tag }}
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Version Tag
        id: set_tag
        run: |
          TAG=$(npm pkg get version | tr -d '"')
          echo "::set-output name=tag::$latest_version"

      - name: Login into GitHub Container Registry
        run: echo "${{ secrets.DEVOPS_BINGO_REGISTRY_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build the Docker Image
        run: |
          docker buildx create --name app --use
          DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64 \
          -t "ghcr.io/slj-inc/devops-bingo:${{ steps.set_tag.outputs.tag }}" --push .

  deploy-development:
    name: Deploy Development
    runs-on: ubuntu-latest
    environment: Development
    needs: build-and-publish
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Deploy on Kapstan Development
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7
        with:
          application_name: wwwdevopsbingo
          image_tag: ${{ needs.build-and-publish.outputs.imageTag }}
          kapstan_api_key: ${{ secrets.DEVOPS_BINGO_KAPSTAN_API_KEY }}
          wait_for_deployment: true

  deploy-prod:
    name: Deploy Production
    runs-on: ubuntu-latest
    environment: Production
    needs: [build-and-publish, deploy-development]
    steps:
      - name: Deploy on Kapstan Production
        id: Kapstan
        uses: kapstan-io/deployment-action@v0.7
        with:
          application_name: devsopsbingo
          image_tag: ${{ needs.build-and-publish.outputs.imageTag }}
          kapstan_api_key: ${{ secrets.DEVOPS_BINGO_KAPSTAN_API_KEY }}
          wait_for_deployment: true